name: build docs

on:
  pull_request:
    branches: [ master ]

jobs:
  build_pages:
    permissions:
      contents: write
    uses: superern/.github/.github/workflows/compile-assets.yml@0.1.0
    secrets: inherit
